
export type Strain = 'Cobb' | 'Ross' | 'Avian' | 'Arbo' | 'IR' | 'Hubbard';

export interface DailyData {
  age: number;
  weight: number; // in grams
  dailyFeed: number; // grams per bird
  cumFeed: number; // cumulative grams per bird
  dailyWater: number; // ml per bird (usually 1.6 - 2.0x feed)
}

export const POULTRY_DATA: Record<Strain, DailyData[]> = {
  Cobb: [
    { age: 1, weight: 42, dailyFeed: 13, cumFeed: 13, dailyWater: 24 },
    { age: 2, weight: 57, dailyFeed: 16, cumFeed: 29, dailyWater: 29 },
    { age: 3, weight: 75, dailyFeed: 19, cumFeed: 48, dailyWater: 34 },
    { age: 4, weight: 97, dailyFeed: 23, cumFeed: 71, dailyWater: 41 },
    { age: 5, weight: 125, dailyFeed: 27, cumFeed: 98, dailyWater: 49 },
    { age: 6, weight: 158, dailyFeed: 32, cumFeed: 130, dailyWater: 58 },
    { age: 7, weight: 198, dailyFeed: 37, cumFeed: 167, dailyWater: 67 },
    { age: 10, weight: 334, dailyFeed: 54, cumFeed: 301, dailyWater: 97 },
    { age: 14, weight: 525, dailyFeed: 72, cumFeed: 542, dailyWater: 130 },
    { age: 21, weight: 1056, dailyFeed: 121, cumFeed: 1211, dailyWater: 218 },
    { age: 28, weight: 1756, dailyFeed: 168, cumFeed: 2178, dailyWater: 302 },
    { age: 35, weight: 2548, dailyFeed: 205, cumFeed: 3450, dailyWater: 369 },
    { age: 40, weight: 3125, dailyFeed: 228, cumFeed: 4500, dailyWater: 410 },
  ],
  Ross: [
    { age: 1, weight: 42, dailyFeed: 13, cumFeed: 13, dailyWater: 23 },
    { age: 2, weight: 58, dailyFeed: 16, cumFeed: 29, dailyWater: 28 },
    { age: 3, weight: 77, dailyFeed: 20, cumFeed: 49, dailyWater: 34 },
    { age: 4, weight: 100, dailyFeed: 24, cumFeed: 73, dailyWater: 41 },
    { age: 5, weight: 128, dailyFeed: 28, cumFeed: 101, dailyWater: 48 },
    { age: 6, weight: 161, dailyFeed: 32, cumFeed: 133, dailyWater: 55 },
    { age: 7, weight: 198, dailyFeed: 36, cumFeed: 161, dailyWater: 65 },
    { age: 10, weight: 325, dailyFeed: 52, cumFeed: 290, dailyWater: 94 },
    { age: 14, weight: 526, dailyFeed: 70, cumFeed: 520, dailyWater: 126 },
    { age: 21, weight: 1059, dailyFeed: 118, cumFeed: 1160, dailyWater: 212 },
    { age: 28, weight: 1741, dailyFeed: 163, cumFeed: 2090, dailyWater: 293 },
    { age: 35, weight: 2524, dailyFeed: 198, cumFeed: 3310, dailyWater: 356 },
    { age: 40, weight: 3083, dailyFeed: 220, cumFeed: 4320, dailyWater: 396 },
  ],
  Avian: [
    { age: 1, weight: 42, dailyFeed: 12, cumFeed: 12, dailyWater: 22 },
    { age: 7, weight: 180, dailyFeed: 35, cumFeed: 154, dailyWater: 63 },
    { age: 10, weight: 312, dailyFeed: 50, cumFeed: 280, dailyWater: 90 },
    { age: 14, weight: 520, dailyFeed: 68, cumFeed: 500, dailyWater: 122 },
    { age: 21, weight: 1000, dailyFeed: 115, cumFeed: 1130, dailyWater: 207 },
    { age: 28, weight: 1600, dailyFeed: 160, cumFeed: 2050, dailyWater: 288 },
    { age: 35, weight: 2280, dailyFeed: 195, cumFeed: 3250, dailyWater: 351 },
    { age: 40, weight: 2750, dailyFeed: 215, cumFeed: 4250, dailyWater: 387 },
  ],
  Arbo: [
    { age: 1, weight: 42, dailyFeed: 13, cumFeed: 13, dailyWater: 24 },
    { age: 7, weight: 198, dailyFeed: 37, cumFeed: 167, dailyWater: 67 },
    { age: 14, weight: 512, dailyFeed: 70, cumFeed: 540, dailyWater: 126 },
    { age: 21, weight: 1025, dailyFeed: 118, cumFeed: 1185, dailyWater: 212 },
    { age: 28, weight: 1720, dailyFeed: 164, cumFeed: 2140, dailyWater: 295 },
    { age: 35, weight: 2515, dailyFeed: 202, cumFeed: 3410, dailyWater: 364 },
    { age: 40, weight: 3050, dailyFeed: 225, cumFeed: 4420, dailyWater: 405 },
  ],
  IR: [
    { age: 1, weight: 42, dailyFeed: 12, cumFeed: 12, dailyWater: 22 },
    { age: 7, weight: 190, dailyFeed: 35, cumFeed: 160, dailyWater: 63 },
    { age: 14, weight: 505, dailyFeed: 68, cumFeed: 525, dailyWater: 122 },
    { age: 21, weight: 1010, dailyFeed: 115, cumFeed: 1150, dailyWater: 207 },
    { age: 28, weight: 1690, dailyFeed: 160, cumFeed: 2100, dailyWater: 288 },
    { age: 35, weight: 2480, dailyFeed: 198, cumFeed: 3320, dailyWater: 356 },
    { age: 40, weight: 3010, dailyFeed: 220, cumFeed: 4350, dailyWater: 396 },
  ],
  Hubbard: [
    { age: 1, weight: 42, dailyFeed: 12, cumFeed: 12, dailyWater: 22 },
    { age: 7, weight: 191, dailyFeed: 34, cumFeed: 158, dailyWater: 61 },
    { age: 14, weight: 498, dailyFeed: 65, cumFeed: 505, dailyWater: 117 },
    { age: 21, weight: 988, dailyFeed: 110, cumFeed: 1120, dailyWater: 198 },
    { age: 28, weight: 1640, dailyFeed: 155, cumFeed: 2050, dailyWater: 279 },
    { age: 35, weight: 2390, dailyFeed: 190, cumFeed: 3250, dailyWater: 342 },
    { age: 40, weight: 2920, dailyFeed: 210, cumFeed: 4280, dailyWater: 378 },
  ],
};

// Interpolation function to get data for any day between 1 and 40
export function getDailyStats(strain: Strain, age: number): DailyData {
  const data = POULTRY_DATA[strain];
  if (age <= 1) return data[0];
  if (age >= 40) return data[data.length - 1];

  let lower = data[0];
  let upper = data[data.length - 1];

  for (let i = 0; i < data.length - 1; i++) {
    if (age >= data[i].age && age <= data[i + 1].age) {
      lower = data[i];
      upper = data[i + 1];
      break;
    }
  }

  const factor = (age - lower.age) / (upper.age - lower.age);
  return {
    age,
    weight: Math.round(lower.weight + (upper.weight - lower.weight) * factor),
    dailyFeed: Math.round(lower.dailyFeed + (upper.dailyFeed - lower.dailyFeed) * factor),
    cumFeed: Math.round(lower.cumFeed + (upper.cumFeed - lower.cumFeed) * factor),
    dailyWater: Math.round(lower.dailyWater + (upper.dailyWater - lower.dailyWater) * factor),
  };
}

// Scientific target temperature profile for industrial broiler management
export function getTargetTemperature(age: number): number {
  const profile = [
    { age: 1, temp: 33 },
    { age: 3, temp: 31 },
    { age: 7, temp: 29 },
    { age: 14, temp: 26 },
    { age: 21, temp: 23 },
    { age: 28, temp: 21 },
    { age: 35, temp: 20 },
    { age: 40, temp: 20 }
  ];

  if (age <= 1) return profile[0].temp;
  if (age >= 40) return profile[profile.length - 1].temp;

  let lower = profile[0];
  let upper = profile[profile.length - 1];

  for (let i = 0; i < profile.length - 1; i++) {
    if (age >= profile[i].age && age <= profile[i + 1].age) {
      lower = profile[i];
      upper = profile[i + 1];
      break;
    }
  }

  const factor = (age - lower.age) / (upper.age - lower.age);
  return Math.round((lower.temp + (upper.temp - lower.temp) * factor) * 10) / 10;
}

export function getTargetHumidity(age: number): { min: number, max: number } {
  if (age <= 7) return { min: 60, max: 70 };
  if (age <= 14) return { min: 55, max: 65 };
  if (age <= 28) return { min: 50, max: 60 };
  return { min: 45, max: 55 };
}

export const CLIMATE_FACTORS = {
  'بارد جدا': { temp: 5, waterFactor: 1.4, ventilationFactor: 0.7 },
  'بارد': { temp: 15, waterFactor: 1.6, ventilationFactor: 0.9 },
  'معتدل': { temp: 25, waterFactor: 1.8, ventilationFactor: 1.2 },
  'حار': { temp: 32, waterFactor: 2.2, ventilationFactor: 1.5 },
  'حار جدا': { temp: 38, waterFactor: 2.8, ventilationFactor: 2.0 },
};

export const MEDICATIONS = [
  // Day 1
  { 
    id: 'd1-ors', 
    name: 'محلول معالجة جفاف', 
    unit: 'جرام/لتر', 
    doseValue: 5, 
    category: 'تأسيس', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [1], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'يعمل على تعويض السوائل والشوارد المفقودة أثناء النقل من المعمل. يحفز الطيور على استهلاك العلف مبكراً عن طريق تنشيط الأنزيمات الهاضمة ورفع طاقة الجسم.', 
    mixingRules: 'يتم إذابة المسحوق في ماء فاتر (25 درجة مئوية) لضمان سرعة الامتصاص. لا يخلط مع المضادات الحيوية في نفس السقية.', 
    technicalSequence: 'يُقدم فور وصول الكتاكيت لتعويض الجفاف الإجهادي، ويتبعه ماء نقي لغسل الفم قبل جرعات الفيتامينات المسائية.',
    tradeNames: 'Rehydran-N, Pedialyte, ORS-Vet' 
  },
  { 
    id: 'd1-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [1], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فترة راحة حيوية تسمح للجهاز الهضمي بتنظيم الضغط الأسموزي بعد جرعة الأملاح المركزة، ومنع حدوث إسهالات ناتجة عن تراكم الشوارد.', 
    mixingRules: 'مياه نظيفة تماماً بدون أي إضافات، وبدرجة حرارة الغرفة.', 
    technicalSequence: 'فاصل راحة إلزامي بين محلول الجفاف وفيتامين C لضمان استقرار الوسط المعوي.' 
  },
  { 
    id: 'd1-vitc', 
    name: 'فيتامين C', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [1], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'يعمل كمضاد إجهاد حراري وفيزيائي، ويحمي جدران الخلايا من الأكسدة أثناء تقلبات درجات الحرارة في اليوم الأول، ويدعم جهاز المناعة الأولي.', 
    mixingRules: 'يُفضل إذابته في كمية صغيرة من الماء أولاً ثم إضافته للخزان. يتأثر بالضوء المباشر لذا يجب تغطية الخزانات.', 
    technicalSequence: 'جرعة ليلية هادئة تسلم لليوم التالي، توفر الاستقرار المطلوب للقلب والأوعية الدموية.',
    tradeNames: 'Vitacid, C-Vit, Ascorbic-Vet' 
  },
  { 
    id: 'd1-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 6, 
    targetDays: [1], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فترة استراحة ختام اليوم لضمان التخلص من متبقيات الإضافات الكيميائية وتحضير المعدة لاستقبال كورس التحضين الأساسي.', 
    mixingRules: 'مياه عذبة نقية.', 
    technicalSequence: 'ختام اليوم الأول، تمهد الطريق لبداية كورس المضاد الحيوي الوقائي في اليوم الثاني.' 
  },

  // Day 2
  { 
    id: 'd2-antibiotic', 
    name: 'مضاد حيوي معوي+تنفسي', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'وقائي', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [2], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    isAntibiotic: true, 
    scientificExplanation: 'يستهدف الميكوبلازما (تنفسي) والسالمونيلا والإيكولاي (معوي) التي قد تنتقل من الأم عبر البيضة. يضمن بداية نظيفة للقطيع وتقليل النافق المبكر.', 
    mixingRules: 'يرج المنتج جيداً قبل الاستخدام. يضاف للماء تدريجياً لضمان الخلط المتجانس. يحظر خلطه مع فيتامينات أحماض عضوية.', 
    technicalSequence: 'يبدأ من الصباح الباكر لضمان أعلى استهلاك خلال فترة النشاط، ويتبعه ماء نقي لراحة الكلى.',
    tradeNames: 'Tylovet, Colistin-Plus, Gentodox' 
  },
  { 
    id: 'd2-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [2], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فاصل تشطيف لخطوط النبل وللجهاز الهضمي، حيث أن تراكم المضادات الحيوية قد يسبب ثقلاً على الكلى في الأعمار الصغيرة.', 
    mixingRules: 'مياه نظيفة.', 
    technicalSequence: 'فاصل حيوي بعد 12 ساعة من العلاج الوقائي المستمر.' 
  },
  { 
    id: 'd2-vitc', 
    name: 'فيتامين C', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [2], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'متابعة دعم القلب وتحسين كفاءة التنفس، وتجهيز الطائر لليوم الثالث من التحضين حيث يبدأ تزايد نشاط الطيور.', 
    mixingRules: 'إذابة تامة في وعاء خارجي أولاً.', 
    technicalSequence: 'جرعة ليلية تدعم الحالة الصحية العامة وتخفف من أثر المضاد الحيوي الصباحي.',
    tradeNames: 'Vitacid, C-Vit, Ascorbic-Vet' 
  },
  { 
    id: 'd2-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [2], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استراحة هضمية قبل دورة النوم الكبرى للقطيع.', 
    mixingRules: 'مياه عذبة.', 
    technicalSequence: 'ختام فعال لليوم الثاني.' 
  },

  // Day 3
  { 
    id: 'd3-antibiotic', 
    name: 'مضاد حيوي معوي+تنفسي', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'وقائي', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [3], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    isAntibiotic: true, 
    scientificExplanation: 'استكمال دورة القضاء على الميكروبات الكامنة. التوقف المبكر يسبب مقاومة بكتيرية (Resistance) مما يجعل العلاج غير فعال مستقبلاً.', 
    mixingRules: 'نفس قواعد اليوم الثاني. يجب التأكد من نظافة التانك من متبقيات الفيتامينات الليلية.', 
    technicalSequence: 'جرعة نهارية مكثفة تعقب جرعة الفيتامينات الليلية، ضرورية لثبات النمو.',
    tradeNames: 'Tylovet, Colistin-Plus, Gentodox' 
  },
  { 
    id: 'd3-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [3], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تشطيف هضمي قبل التحول لنوع آخر من الإضافات لتجنب التفاعلات الدوائية.', 
    mixingRules: 'مياه نقية عذبة.', 
    technicalSequence: 'فاصل راحة للأمعاء يمهد لاستقبال فيتامينات النمو الأساسية.' 
  },
  { 
    id: 'd3-ad3e', 
    name: 'فيتامينات أد3هـ', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [3], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تأسيس الهيكل العظمي (فيتامين D) وتدعيم الأغشية المخاطية والجهاز التنفسي (فيتامين A) وتحفيز الخصوبة والنمو (فيتامين E).', 
    mixingRules: 'يُفضل إضافته لماء بارد لأن فيتامين A حساس للحرارة والضوء.', 
    technicalSequence: 'جرعة ليلية تدعم التكوين البنائي للطائر خلال فترة الراحة الليلية.',
    tradeNames: 'Vitane AD3E, AD3E-Plus, Veto-AD3E' 
  },
  { 
    id: 'd3-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [3], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية لمنع التركيزات الملحية العالية قبل يوم ختام الكورس الوقائي.', 
    mixingRules: 'مياه شرب نقية.', 
    technicalSequence: 'ختام اليوم الثالث بنجاح.' 
  },

  // Day 4
  { 
    id: 'd4-antibiotic', 
    name: 'جرعة مضاد حيوي معوي+تنفسي', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'وقائي', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [4], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    isAntibiotic: true, 
    scientificExplanation: 'تأكيد الخلو من ميكروبات المعمل أو ميكروبات الفرشة المبكرة. هذا اليوم هو الحاسم لضمان أمعاء نظيفة قبل البدء في رفع المناعة.', 
    mixingRules: 'الالتزام التام بالنسب المقررة. يفضل استخدام مياه مفلترة لرفع كفاءة الدواء.', 
    technicalSequence: 'جرعة نهارية نهائية للمضاد الحيوي، تليها فترة راحة لتنظيف الجهاز البولي.',
    tradeNames: 'Tylovet, Colistin-Plus, Gentodox' 
  },
  { 
    id: 'd4-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [4], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فاصل تشطيف ضروري للتخلص من مرارة طعم المضاد الحيوي وتحفيز الشهية للعلف.', 
    mixingRules: 'مياه عذبة.', 
    technicalSequence: 'راحة نبل وتنظيف لخطوط الشرب.' 
  },
  { 
    id: 'd4-ad3e', 
    name: 'فيتامينات أد3هـ', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [4], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'دعم النمو المتسارع للهيكل العظمي، خاصة في سلاسل مثل Cobb و Ross التي تمتاز بسرعة التحويل الغذائي.', 
    mixingRules: 'يضاف للخزان مع تغطيته. يفضل التقليب المستمر لضمان عدم ترسب الفيتامينات الزيتية.', 
    technicalSequence: 'جرعة ليلية تدعم طفرة النمو المتوقعة في نهاية الأسبوع الأول.',
    tradeNames: 'Vitane AD3E, AD3E-Plus, Veto-AD3E' 
  },
  { 
    id: 'd4-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [4], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استراحة قبل التحول لمنهجية البكتيريا النافعة (Probiotics) في اليوم الخامس.', 
    mixingRules: 'مياه نظيفة.', 
    technicalSequence: 'تأمين استقرار معوي.' 
  },

  // Day 5
  { 
    id: 'd5-pro', 
    name: 'بروبيوتيك (بكتريا نافعة)', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'تأسيس', 
    usageType: 'ضروري', 
    recommendedHours: 4, 
    targetDays: [5], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استعمار الأمعاء بالبكتيريا الصديقة لمنع الميكروبات الضارة من الالتصاق بجدران الأمعاء (Competitive Exclusion). تفرز أنزيمات هاضمة طبيعية ترفع كفاءة الاستفادة من العلف.', 
    mixingRules: 'تحذير: لا يخلط مع أي مضاد حيوي أو مطهرات (كلور). يستخدم ماء مفلتر أو ماء بئر نظيف.', 
    technicalSequence: 'جرعة صباحية نهارية ناعمة، تعقب كورس المضادات لتجديد الوسط البكتيري للأمعاء.',
    tradeNames: 'Bio-Top, Pro-B, Bactocin' 
  },
  { 
    id: 'd5-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [5], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تطهير القنوات الهضمية ومنع حدوث تخمرات بكتيرية ناتجة عن السكريات الحاملة للبروبيوتيك.', 
    mixingRules: 'مياه نقية جداً.', 
    technicalSequence: 'فاصل بيولوجي لحماية البكتيريا النافعة من التكسر الكيميائي.' 
  },
  { 
    id: 'd5-toxin', 
    name: 'مضاد سموم فطرية', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'سموم', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [5], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'حماية خلايا الكبد والكلى من السموم الفطرية الكامنة في العلف. يعمل على رفع معدلات التمثيل الغذائي وتنقية الدم.', 
    mixingRules: 'يذاب في كمية كبيرة من الماء. يرج العبوة جيداً لاحتوائها على رواسب مفيدة.', 
    technicalSequence: 'جرعة نهارية وقائية هامة جداً لضمان استمرارية النمو بدون عرقلة كبدية.',
    tradeNames: 'Anti-Tox, Toxi-Guard, Myco-Nil' 
  },
  { 
    id: 'd5-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [5], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة هضمية وتخفيف الضغط على الكلى بعد جرعة مضاد السموم.', 
    mixingRules: 'مياه شرب عذبة.', 
    technicalSequence: 'فاصل قبل جرعة الأملاح المعدنية الليلية.' 
  },
  { 
    id: 'd5-elec', 
    name: 'إليكتروليت (أملاح معدنية)', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'داعم', 
    usageType: 'ضروري', 
    recommendedHours: 6, 
    targetDays: [5], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'منع الجفاف الناتج عن سرعة التنفس (Pant) في الأجواء الحارة، وتعويض الأملاح المفقودة في الزرق لتنظيم ضربات القلب.', 
    mixingRules: 'إذابة تامة حتى يختفي الراسب. لا تزد الجرعة عن الموصى بها لتجنب الإسهالات الملحية.', 
    technicalSequence: 'جرعة ليلية توفر التوازن الأسموزي اللازم لفترة النوم الهادئة.',
    tradeNames: 'Punch, Electrolyte-Vet, Hydra-Charge' 
  },
  { 
    id: 'd5-water3', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [5], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'غسيل للأمعاء لمنع ترسب الأملاح في الكلى أو الحالب.', 
    mixingRules: 'مياه عذبة ونقية.', 
    technicalSequence: 'ختام اليوم الخامس وتحضير لليوم السادس (ما قبل التحصين).' 
  },

  // Day 6
  { 
    id: 'd6-pro', 
    name: 'بروبيوتيك (بكتريا نافعة)', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'تأسيس', 
    usageType: 'ضروري', 
    recommendedHours: 4, 
    targetDays: [6], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'إكمال دورة استعمار البكتيريا النافعة وتثبيتها في الزغابات المعوية قبل صدمة التحصين في اليوم السابع. تضمن مناعة معوية صلبة.', 
    mixingRules: 'استخدام ماء مفلتر حصراً. لا تضعه في التانك إذا تم استخدام الكلور في الـ 12 ساعة الماضية.', 
    technicalSequence: 'جرعة صباحية نهارية مبكرة لضمان بيئة معوية مثالية.',
    tradeNames: 'Bio-Top, Pro-B, Bactocin' 
  },
  { 
    id: 'd6-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [6], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استراحة هضمية لمنع التنافس بين البكتيريا النافعة والفيتامينات اللاحقة.', 
    mixingRules: 'مياه نظيفة تماماً.', 
    technicalSequence: 'فاصل حيوي هام قبل البدء في فيتامينات رفع الكفاءة المناعية.' 
  },
  { 
    id: 'd6-ese', 
    name: 'فيتامينات هـ + سيلينيوم', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [6], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'أقوى تركيبة لرفع كفاءة الجهاز المناعي قبل التحصين بـ 24 ساعة. يعمل السيلينيوم كمحفز لإنتاج الأجسام المضادة (Antibodies).', 
    mixingRules: 'يُرج جيداً ويضاف للخزان. يفضل استخدامه في ساعات الظهيرة لتقليل الإجهاد التأكسدي.', 
    technicalSequence: 'جرعة نهارية حيوية، تعتبر حجر الزاوية لنجاح تحصينة اليوم السابع.',
    tradeNames: 'E-Selen, Vit-E-Plus, Se-Guard' 
  },
  { 
    id: 'd6-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [6], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تأمين استقرار حيوي وتخفيف الضغط على القلب الناتج عن منشطات النمو.', 
    mixingRules: 'مياه عذبة.', 
    technicalSequence: 'فاصل راحة استعداداً لجرعة الأملاح الليلية.' 
  },
  { 
    id: 'd6-elec', 
    name: 'جرعة إليكتروليت (أملاح معدنية)', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'داعم', 
    usageType: 'ضروري', 
    recommendedHours: 6, 
    targetDays: [6], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تنشيط مراكز العطش والشرب لدى الطائر لضمان اقباله الشديد على ماء التحصين في الصباح، وتوفير الأملاح اللازمة لنقل الفيروس الضعيف.', 
    mixingRules: 'إذابة كلية. تأكد من عدم وجود رواسب قد تغلق فتحات النبل.', 
    technicalSequence: 'جرعة ليلية استراتيجية لتحضير الطائر بدنياً لعملية التحصين.',
    tradeNames: 'Punch, Electrolyte-Vet, Hydra-Charge' 
  },
  { 
    id: 'd6-water3', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [6], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'غسيل نهائي للأمعاء والخطوط من أي متبقيات كيماوية قد تقتل فيروس اللقاح الحي غداً.', 
    mixingRules: 'مياه عذبة نقية جداً وخالية من أي مطهرات.', 
    technicalSequence: 'ختام اليوم السادس وتحضير نهائي ليوم التحصين الأكبر.' 
  },

  // Day 7
  { 
    id: 'd7-thirst', 
    name: 'تعطيش', 
    unit: 'ساعة', 
    doseValue: 2, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [7], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تحفيز حاجة الطائر الغريزية لشرب الماء لضمان استهلاك كمية اللقاح كاملة في وقت قياسي (أقل من ساعة) قبل موت الفيروس.', 
    mixingRules: 'رفع كافة المساقي (أوتوماتيك ويدوي) وجفاف الخطوط تماماً. ممنوع منعاً باتاً زيادة المدة عن ساعتين.', 
    technicalSequence: 'تبدأ في الصباح الباكر، وتعتبر التمهيد العملي للتأكد من وصول اللقاح لكل فرد في القطيع.' 
  },
  { 
    id: 'd7-milk', 
    name: 'مثبت لقاح (حليب)', 
    unit: 'جرام/لتر', 
    doseValue: 2, 
    category: 'تحصين', 
    usageType: 'ضروري', 
    recommendedHours: 0.5, 
    targetDays: [7], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'يعمل على معادلة الكلور والأملاح المعدنية الثقيلة في الماء التي قد تقتل الفيروس الحي باللقاح، ويوفر غطاءً بروتينياً يحمي الفيروس.', 
    mixingRules: 'يذاب في مياه مبردة (6-10 درجات مئوية). يجب أن يكون منزوع الدسم تماماً لمنع انسداد النبل.', 
    technicalSequence: 'يُقدم قبل فتح أمبول اللقاح بـ 20 دقيقة لضمان أمان الوسط المائي وتطهير الخطوط من المعقمات.' 
  },
  { 
    id: 'd7-vac', 
    name: 'تحصين هيتشنر ب1 + أي بي', 
    unit: 'أمبول', 
    doseValue: 1, 
    category: 'تحصين', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [7], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فيروس حي ضعيف يحفز الجهاز المناعي لإنتاج أجسام مضادة ضد مرض النيوكاسل والتهاب الشعب الهوائية المعدي. حجر الأساس لمنع الكوارث الفيروسية.', 
    mixingRules: 'يُفتح الأمبول تحت سطح الماء المضاف إليه مثبت اللقاح. ممنوع ملامسة اللقاح لليد البشرية مباشرة أو التعرض للحرارة.', 
    technicalSequence: 'توزع الكمية على كافة المساقي بالتساوي، ويجب التأكد من استهلاكها كاملة خلال 60-90 دقيقة كحد أقصى.',
    tradeNames: 'Cevac iBIRD, Nobilis IB+Ma5, Hitchner B1' 
  },
  { 
    id: 'd7-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [7], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تأمين استقرار الفيروس في الغدد المناعية بالحلق والأمعاء، ومنع حدوث مضاعفات ثانوية نتيجة الإجهاد.', 
    mixingRules: 'مياه نظيفة بدون إضافات.', 
    technicalSequence: 'فترة راحة ما بعد التحصين (Post-Vaccination Rest) لضمان هدوء القطيع.' 
  },
  { 
    id: 'd7-ad3e', 
    name: 'فيتامينات أد3هـ', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [7], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استخدام فيتامينات A و E لترميم الأغشية المخاطية التي تأثرت باحتكاك الفيروس ورفع كفاءة البناء العظمي والبدني.', 
    mixingRules: 'يضاف للخزان مباشرة مع تقليب جيد.', 
    technicalSequence: 'جرعة ليلية حيوية جداً لإعادة التوازن للجسم بعد يوم تحصين شاق.',
    tradeNames: 'Vitane AD3E, AD3E-Plus, Veto-AD3E' 
  },
  { 
    id: 'd7-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [7], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية ختامية للأمعاء لتنظيف متبقيات اللبن والفيتامينات قبل بداية الأسبوع الثاني.', 
    mixingRules: 'مياه عذبة نقية.', 
    technicalSequence: 'ختام يوم التحصين الأول بنجاح (نهاية الأسبوع الأول).' 
  },

  // Day 8
  { 
    id: 'd8-hepato', 
    name: 'منشط كبد', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'كلوي/كبد', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [8], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'يعمل على تنشيط خلايا الكبد المتعبة من كورس التحضين الأولي، ويحفز إفراز العصارة الصفراوية لتحسين هضم الدهون في علف البادي. يساعد في طرد السموم المتبقية ورفع كفاءة التمثيل الغذائي.', 
    mixingRules: 'يُرج جيداً قبل الاستخدام (لوجود رواسب طبيعية أحياناً). يضاف للماء في الصباح الباكر لضمان امتصاصه مع ذروة النشاط. لا يخلط مع المضادات الحيوية.', 
    technicalSequence: 'بداية الأسبوع الثاني تتطلب تنظيف الكبد لرفع معدل التحويل؛ لذا يُقدم كأول جرعة في اليوم الثامن، ويتبعه ماء نقي للراحة.',
    tradeNames: 'Hepato-Vet, Liver-Active, Hepa-Plus' 
  },
  { 
    id: 'd8-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [8], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فترة استراحة ضرورية للسماح للكبد بمعالجة الجرعة المنشطة دون تداخلات، ومنع التفاعلات الكيميائية في حال وجود متبقيات معدنية في الخطوط.', 
    mixingRules: 'ماء نقي تماماً، يفضل بئر أو مفلتر، خالي من أي إضافات وبدرجة حرارة الغرفة.', 
    technicalSequence: 'فاصل زمني إلزامي بين المنشط الكبدي وفيتامينات النمو الليلية لضمان ثبات الامتصاص وعدم حدوث "تزاحم" كيميائي.' 
  },
  { 
    id: 'd8-ad3e', 
    name: 'فيتامين أد3هـ', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [8], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'متابعة بناء الهيكل العظمي في مرحلة تسارع النمو؛ فيتامين D3 يضمن تثبيت الكالسيوم، وفيتامين A يدعم سلامة الأغشية المخاطية للأمعاء والجهاز التنفسي.', 
    mixingRules: 'يخلط في ماء بارد بعيداً عن أشعة الشمس المباشرة. يفضل استخدام وعاء خارجي للخلط التدريجي ثم الإضافة للخزان لضمان تجانس المادة الزيتية.', 
    technicalSequence: 'جرعة ليلية طويلة تدعم النمو الهادئ وتوفر للجسم العناصر البنائية اللازمة للأنسجة والعظام الجديدة خلال فترة السكون.',
    tradeNames: 'Vitane AD3E, AD3E-Plus, Veto-AD3E' 
  },
  { 
    id: 'd8-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [8], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'غسيل لخطوط الشرب من المتبقيات الزيتية للفيتامينات، ومنع تكوين الطبقة اللزجة (Biofilm) التي تجذب البكتيريا الضارة.', 
    mixingRules: 'مياه عذبة ونظيفة، يفضل التأكد من ضغط المياه داخل المواسير لضمان التشطيف.', 
    technicalSequence: 'ختام اليوم الثامن لضمان تفريغ المواسير من أي مواد عضوية، مما يمهد الطريق لبداية نظيفة في اليوم التاسع.' 
  },

  // Day 9
  { 
    id: 'd9-bk', 
    name: 'فيتامين B-K (ب.ك كولين)', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [9], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فيتامين B مركب ضروري لتمثيل البروتين وتنظيم الجهاز العصبي، بينما فيتامين K يحمي الشعيرات الدموية من النزيف المعوي الناتج عن توسع الأمعاء السريع.', 
    mixingRules: 'يذاب جيداً ويضاف للخزان. يفضل استهلاك السقية خلال 8 ساعات للحفاظ على استقرار الفيتامينات الحساسة للضوء.', 
    technicalSequence: 'جرعة نهارية استباقية لدعم جدران الأمعاء والتمثيل الغذائي في ذروة استهلاك العلف اليومي.',
    tradeNames: 'B-Complex Plus, Liver-Tone, Vit-B-K' 
  },
  { 
    id: 'd9-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [9], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة هضمية تساعد الأمعاء على امتصاص العناصر الغذائية من العلف دون تداخل كيميائي خارجي، وتسمح للكلى بتصريف الأملاح.', 
    mixingRules: 'مياه نظيفة تماماً خالية من أي إضافات، وبدرجة حرارة مريحة للطيور.', 
    technicalSequence: 'فاصل زمني ضروري لإعادة التوازن المعوي الكيميائي (pH) قبل تقديم جرعة الأملاح المعدنية المسائية.' 
  },
  { 
    id: 'd9-elec', 
    name: 'إليكتروليت (أملاح معدنية)', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'داعم', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [9], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'موازنة الضغط الأسموزي في الدم، مما يحمي الطائر من الإجهاد التنفسي والجفاف, ويدعم عمل القلب والأعصاب في ظل التحويل الغذائي الكثيف.', 
    mixingRules: 'إذابة تامة ومكثفة لضمان عدم ترسب الأملاح في نهايات الخطوط أو داخل "التانك". تجنب زيادة الجرعة لمنع حدوث إسهالات ملحية.', 
    technicalSequence: 'جرعة ليلية هادئة تعوض الفقد اليومي من الأملاح وتدعم استجابة الطيور لشرب الماء بكفاءة تامة.',
    tradeNames: 'Punch, Electrolyte-Vet, Hydra-Charge' 
  },
  { 
    id: 'd9-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [9], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تشطيف نهائي للحفاظ على سلامة حلمات الشرب (Nipples) من الانسداد الملحي الميكروسكوبي، وتنظيف الوسط الفموي للطيور.', 
    mixingRules: 'مياه عذبة عادية بدون إضافات.', 
    technicalSequence: 'ختام آمن لليوم التاسع لضمان جاهزية النظام لمرحلة اليوم العاشر.' 
  },

  // Day 10
  { 
    id: 'd10-bk', 
    name: 'فيتامين B-K (ب.ك كولين)', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [10], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استكمال جرعات تدعيم الأنسجة والتمثيل الغذائي لضمان أعلى معدل تحويل خلال نهاية المرحلة الأولى من عمر الطائر، وتوفير مخزون من فيتامين K للأوعية الدموية.', 
    mixingRules: 'يضاف للخزان مباشرة مع تقليب مستمر لضمان التوزيع العادل لكل لتر ماء يشربه الطائر.', 
    technicalSequence: 'جرعة نهارية طويلة تغطي ساعات النشاط القصوى، تمهد ليوم الراحة العالمي للقطيع في نهاية الأسبوع.',
    tradeNames: 'B-Complex Plus, Vit-B-K' 
  },
  { 
    id: 'd10-water', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [10], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'يوم الراحة العضوية الشامل؛ يسمح للجسم (كلى، كبد، أمعاء) بالتخلص الكامل من متبقيات الأدوية وتجديد حيوية الخلايا بصورة طبيعية تماماً.', 
    mixingRules: 'مياه وفيرة جداً، نقية، بدرجة حرارة الغرفة (لا باردة ولا ساخنة).', 
    technicalSequence: 'راحة ليلية ونهارية ختامية للمرحلة الأولى، تحضيراً لبروتوكول الأسبوع الثاني الحاسم.' 
  },

  // Day 11
  { 
    id: 'd11-ese', 
    name: 'فيتامين هـ + سيلينيوم', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [11], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'يحفز الجهاز المناعي بقوة قبل موعد تحصينة الجمبورو بـ 24 ساعة. يعمل السيلينيوم كمضاد أكسدة يحمي خلايا القلب والعضلات من الإجهاد الناتج عن سرعة النمو المتوقعة في الأسبوع الثاني.', 
    mixingRules: 'يرج جيداً قبل الاستخدام. يفضل خلطه في ماء فاتر لسهولة الانتشار. لا يخلط مع مركبات الحديد أو النحاس في نفس الخزان.', 
    technicalSequence: 'جرعة ليلية تمهيدية لرفع جاهزية "جراب فبريشيا" (Bursa of Fabricius) لاستقبال اللقاح في اليوم التالي، وتوفير الحماية الخلوية المطلوبة.',
    tradeNames: 'E-Selen, Vit-E-Plus, Se-Guard' 
  },
  { 
    id: 'd11-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [11], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تطهير الأمعاء ومنع تداخل الفيتامينات السابقة مع فيتامين C اللاحق، ولضمان جفاف خطوط الشرب نسبياً قبل فترة التعطيش الفنية.', 
    mixingRules: 'ماء نقي تماماً، مصفى من الشوائب ومعدل الحرارة.', 
    technicalSequence: 'فاصل راحة قصير وبنّاء يمهد للوسط المائي اللازم لفعالية فيتامين C الصباحي.' 
  },
  { 
    id: 'd11-vitc', 
    name: 'فيتامين C', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [11], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'يعمل كمثبت للحالة الفيزيولوجية للقطيع ويقلل من إفراز هرمون "الكورتيزول" المسبب للإجهاد، مما يجعل استجابة الطيور المناعية للقاح الجمبورو أفضل وأكثر توازناً.', 
    mixingRules: 'إذابة كاملة ومباشرة في الماء. حساس جداً للضوء والحرارة العالية لذا يجب تغطية الخزانات واستهلاك السقية خلال ساعات الصباح.', 
    technicalSequence: 'جرعة نهارية تبرد جسم الطائر وتجعله في حالة استرخاء بدني وعصبي قبل صدمة التعطيش والتحصين المجهدة في اليوم الثاني عشر.',
    tradeNames: 'Vitacid, C-Vit, Ascorbic-Vet' 
  },
  { 
    id: 'd11-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [11], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية ختامية لليوم الحادي عشر لضمان إفراغ الأمعاء من أي متبقيات كيميائية قد تؤثر على الرقم الهيدروجيني للماء.', 
    mixingRules: 'مياه عذبة نظيفة خالية من المطهرات.', 
    technicalSequence: 'ختام اليوم تمهيداً لبدء إجراءات التحصين الصباحية الدقيقة في اليوم التالي.' 
  },

  // Day 12
  { 
    id: 'd12-thirst', 
    name: 'تعطيش', 
    unit: 'ساعة', 
    doseValue: 2, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [12], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'إثارة غريزة العطش لضمان شرب اللقاح بسرعة فائقة وبشكل جماعي، مما يمنع تعرض الفيروس الحي للظروف الجوية لفترة طويلة تفقده فاعليته وتضمن وصوله لكل الطيور.', 
    mixingRules: 'رفع كافة المساقي (الأوتوماتيك واليدوية) وتجفيف الخطوط تماماً. مدة التعطيش تعتمد على حرارة العنبر (ساعة في الصيف، ساعتان في الشتاء). راقب حيوية القطيع.', 
    technicalSequence: 'إجراء فني حرج جداً؛ النجاح فيه يضمن تغطية مناعية 100% للقطيع ومنع حدوث فجوات مناعية تسمح باختراق المرض.' 
  },
  { 
    id: 'd12-vac', 
    name: 'تحصين جمبورو', 
    unit: 'أمبول', 
    doseValue: 1, 
    category: 'تحصين', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [12], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فيروس حي مستضعف يحفز "غدة البرسا" لإنتاج الأجسام المضادة ضد مرض الجمبورو الفتاك الذي يدمر المناعة المكتسبة في الطيور.', 
    mixingRules: 'فتح الأمبول تحت سطح الماء المبرد (8-12 درجة) مع إضافة لبن منزوع الدسم أو مثبت لقاح تجاري. يمنع وجود أي متبقيات للكلور في الماء أو الخطوط نهائياً.', 
    technicalSequence: 'التوزيع السريع والمتكافئ على كافة المشربيات، ويجب التأكد من استهلاك الكمية كاملة خلال 60 دقيقة كحد أقصى للحفاظ على "قوة" الفيروس.',
    tradeNames: 'Cevac Gumbo L, Nobilis Gumboro, 228E' 
  },
  { 
    id: 'd12-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [12], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'توفير فترة هدوء فيسيولوجي بعد التحصين للسماح للفيروس بالارتباط بالمواقع المناعية (Receptors) المستهدفة دون تشويش كيميائي أو دوائي مفاجئ.', 
    mixingRules: 'ماء نقي خالي تماماً من أي مطهرات أو إضافات، وبكمية وفيرة لتعويض العطش السابق.', 
    technicalSequence: 'فترة راحة ما بعد التحصين (Post-Vaccination) لتقليل رد فعل اللقاح المجهد (Vaccine Reactions) وضمان هدوء العنبر.' 
  },
  { 
    id: 'd12-ad3e', 
    name: 'فيتامينات أد3هـ', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [12], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'ترميم الأنسجة اللمفاوية والمخاطية التي تأثرت بارتباط الفيروس، ودعم النمو البدني السريع للقطيع بعد الإجهاد الكبير ليوم التحصين.', 
    mixingRules: 'خلط جيد في وعاء خارجي ثم الإضافة للخزان لضمان التوزيع المتجانس للفيتامينات الزيتية. يفضل تغطية فتحات التانك.', 
    technicalSequence: 'جرعة ليلية طويلة تعوض الطائر عن مجهود اليوم الاستثنائي وترفع من كفاءته البدنية لمواصلة النمو في الأسبوع الثالث.',
    tradeNames: 'Vitane AD3E, AD3E-Plus, Veto-AD3E' 
  },
  { 
    id: 'd12-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [12], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية ختامية وغسيل لخطوط الشرب من متبقيات حليب اللقاح والفيتامينات الزيتية.', 
    mixingRules: 'مياه عذبة نقية.', 
    technicalSequence: 'ختام ناجح ليوم التحصين الحرج والأكثر تأثيراً في دورة التسمين.' 
  },

  // Day 13
  { 
    id: 'd13-vitc', 
    name: 'فيتامين C', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 6, 
    targetDays: [13], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'امتصاص أثر رد فعل اللقاح (Vaccination Reaction) ومنع الارتفاعات الطفيفة في حرارة الجسم الناتجة عن النشاط المناعي المكثف للجسم.', 
    mixingRules: 'إذابة كلية وفورية في كمية ماء كافية لـ 6 ساعات نشاط. يمنع تعرض الماء المضاف إليه الفيتامين لضوء الشمس المباشر.', 
    technicalSequence: 'جرعة صباحية نهارية لتبريد القطيع داخلياً وضمان استقرار الحالة الصحية العامة بعد التحصين.' 
  },
  { 
    id: 'd13-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [13], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'غسيل كلوي طبيعي وتشطيف تشريحي للمعدة لضمان عدم تراكم متبقيات الفيتامينات أو اللقاح في القنوات الهاضمة.', 
    mixingRules: 'مياه عذبة نقية وبكمية وفيرة.', 
    technicalSequence: 'فاصل راحة بيولوجي بين فيتامين C وفيتامينات B-K لضمان أعلى كفاءة امتصاص لكل منهما.' 
  },
  { 
    id: 'd13-bk', 
    name: 'جرعة فيتامين B-K (ب.ك كولين)', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [13], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'حماية جدران الأمعاء من أي التهابات ثانوية قد تنشط بعد الإجهاد المناعي، وتوفير فيتامينات الطاقة اللازمة لمواصلة طفرة النمو.', 
    mixingRules: 'خلط متوازن وتقليب جيد في الخزان الرئيسي لضمان ذوبان مركب الكولين (Choline) الهام للكبد.', 
    technicalSequence: 'جرعة هامة جداً لاستعادة استقرار الحالة الهضمية والتمثيل الغذائي بعد اضطرابات يوم التحصين السابق.',
    tradeNames: 'Hepatic-Choline, B-Complex Plus, Liver-Tone' 
  },
  { 
    id: 'd13-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [13], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة هضمية لمنع التنافس الكيميائي بين الفيتامينات ومضادات السموم اللاحقة.', 
    mixingRules: 'مياه نظيفة ناصعة.', 
    technicalSequence: 'فاصل راحة للأمعاء يسبق جرعة مضاد السموم المسائية لضمان فاعلية التطهير الكبدي.' 
  },
  { 
    id: 'd13-toxin', 
    name: 'مضاد سموم فطرية', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'سموم', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [13], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'التخلص من السموم الفطرية الكامنة، وحماية خلايا الكبد من مجهود يوم التحصين، وتطهير الدم من نواتج التفاعلات الحيوية.', 
    mixingRules: 'يضاف للخزان مباشرة مع رج العبوة جيداً. يفضل استخدام المياه العذبة لرفع كفاءة المواد البيولوجية الفعالة.', 
    technicalSequence: 'جرعة وقائية ليلية تؤمن استقرار الكبد لبداية الأسبوع الثالث (مرحلة النامي) وضمان استمرار النمو المتسارع.' 
  },
  { 
    id: 'd13-water3', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [13], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استراحة وتطهير نهائي للمواسير والخطوط.', 
    mixingRules: 'مياه شرب عادية نقية.', 
    technicalSequence: 'ختام اليوم الثالث عشر واستعداد ليوم الغسيل الكلوي الشامل.' 
  },

  // Day 14
  { 
    id: 'd14-renal', 
    name: 'غسيل كلوي', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'كلوي/كبد', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [14], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تنظيف الأنابيب الكلوية من الأملاح المترسبة ومخلفات الأدوية والبروتينات المعقدة والسموم، مما يمنع حدوث "الفشل الكلوي" أو "النقرس" في المراحل المتقدمة.', 
    mixingRules: 'يستخدم بتركيز 1 سم لكل لتر ماء. يفضل استخدامه في الصباح الباكر مع ذروة نشاط الكلية الطبيعي لرفع كفاءة الطرح الكلوي.', 
    technicalSequence: 'جرعة صباحية نهارية؛ خطوة وقائية جوهرية لنظافة الجسم داخلياً قبل طفرة الوزن الكبرى المتوقعة في الأسبوع الثالث.',
    tradeNames: 'Renal-V, Nephro-Guard, Kidney-Clean' 
  },
  { 
    id: 'd14-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [14], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية وتشطيف لخطوط الشرب من متبقيات الأملاح الكلوية، وتحفيز للشهية قبل جرعة منشط الكبد الطويلة.', 
    mixingRules: 'مياه ناصعة عذبة.', 
    technicalSequence: 'فاصل زمني فني يربط بين عملية التنظيف الكلوي وعملية التنشيط الكبدي لعدم إجهاد أعضاء الطائر.' 
  },
  { 
    id: 'd14-hepato', 
    name: 'منشط كبد', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'كلوي/كبد', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [14], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تحفيز خلايا الكبد لإنتاج الأنزيمات وإفراز الصفراء، مما يرفع من قدرة الطائر القصوى على هضم وتمثيل كميات العلف المتزايدة يوماً بعد يوم.', 
    mixingRules: 'يقلب جيداً في الخزان. يفضل استخدامه في ساعات المساء حيث ينشط الكبد في عمليات البناء والتمثيل خلال فترة السكون.', 
    technicalSequence: 'جرعة مسائية طويلة الأمد لتعظيم الاستفادة الغذائية من وجبة العلف الليلية وتحقيق أعلى معدل تحويل (FCR) ممكن.',
    tradeNames: 'Hepato-Vet, Liver-Active, Hepa-Plus' 
  },
  { 
    id: 'd14-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [14], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية ختامية للأسبوع الثاني وتطهير للجهاز الهضمي.', 
    mixingRules: 'مياه شرب عادية ونظيفة.', 
    technicalSequence: 'ختام اليوم الرابع عشر؛ نهاية مرحلة التحبب وبداية مرحلة التسمين الحقيقية (الأسبوع الثالث).' 
  },

  // Day 15
  { 
    id: 'd15-ese', 
    name: 'فيتامين هـ + سيلينيوم', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [15], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'دعم المناعة العامة وتقوية عضلة القلب لمواكبة تضخم حجم الجسم المتسارع، استعداداً لمرحلة علف النامي (Grower) وحماية الأنسجة من الأكسدة.', 
    mixingRules: 'خلط متجانس في الخزان. لا تزد الجرعة عن الموصى بها لتجنب الإجهاد المعدني على الكلية في بداية الأسبوع الثالث.', 
    technicalSequence: 'جرعة صباحية نهارية لرفع حيوية القطيع وضمان جاهزيته للنشاط البدني المتزايد.' 
  },
  { 
    id: 'd15-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [15], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة فيسيولوجية للكبد والأمعاء قبل البدء في جرعات تدعيم الوسط الهضمي.', 
    mixingRules: 'مياه نظيفة تماماً.', 
    technicalSequence: 'فاصل راحة ضروري يسبق تقديم فيتامين C لتجنب أي تداخلات كيميائية ضارة.' 
  },
  { 
    id: 'd15-vitc', 
    name: 'فيتامين C', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 4, 
    targetDays: [15], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تخفيف حدة الإجهاد وزيادة مقاومة الشعيرات الدموية، وتجهيز الطائر لتقبل التغير في نوعية العلف (من بادي إلى نامي).', 
    mixingRules: 'يذاب تماماً ويستهلك في فترة زمنية قصيرة لضمان أعلى فاعلية.', 
    technicalSequence: 'جرعة مسائية خفيفة تهدف لتهدئة القطيع ورفع كفاءة الجهاز الدوري.' 
  },
  { 
    id: 'd15-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [15], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'غسيل طبيعي للأمعاء لتطهير الوسط الهضمي من متبقيات الفيتامينات السكرية التي قد تسبب تخمرات بكتيرية.', 
    mixingRules: 'مياه عذبة ونقية.', 
    technicalSequence: 'فاصل راحة إلزامي يسبق جرعة الأحماض العضوية الليلية لضمان عدم حدوث فوران كيميائي.' 
  },
  { 
    id: 'd15-acids', 
    name: 'أحماض عضوية', 
    unit: 'سم³/لتر', 
    doseValue: 0.5, 
    category: 'داعم', 
    usageType: 'ضروري', 
    recommendedHours: 6, 
    targetDays: [15], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'خفض الرقم الهيدروجيني للأمعاء (pH)، مما يخلق بيئة طاردة للبكتيريا الضارة ومنشطة للأنزيمات الهاضمة، مما يرفع كفاءة التحويل الغذائي بشكل ملحوظ.', 
    mixingRules: 'يضاف بحذر حسب تركيز المنتج. يراعى عدم خلطه مع المضادات الحيوية في نفس السقية أو في وقت متقارب جداً.', 
    technicalSequence: 'جرعة ليلية تدعم الهضم وتؤمن سلامة الأمعاء من الميكروبات الانتهازية خلال فترة النوم الهادئ للقطيع.',
    tradeNames: 'Acid-Way, Pro-Acid, Formic-Vet' 
  },
  { 
    id: 'd15-water3', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [15], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية شاملة وتطهير نهائي.', 
    mixingRules: 'مياه نظيفة.', 
    technicalSequence: 'ختام اليوم الخامس عشر؛ بداية منهجية الأسبوع الثالث لتدعيم النمو.' 
  },

  // Day 16
  { 
    id: 'd16-cox', 
    name: 'مضاد كوكسيديا', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'وقائي', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [16], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استهداف طفيليات الكوكسيديا التي تهاجم خملات الأمعاء وتسبب النزيف المعوي وفشل التحويل الغذائي. هذه الدورة الوقائية تمنع انفجار دورة حياة الطفيل في هذا العمر الحرج والنشط.', 
    mixingRules: 'إذابة تامة ومكثفة لضمان عدم وجود رواسب. يمنع خلطه مع مضادات الكلوستريديا في نفس الخزان لتجنب التعارض الكيميائي.', 
    technicalSequence: 'جرعة نهارية (10 ساعات) لضمان أعلى معدل استهلاك مائي خلال فترة نشاط الطيور، تليها فترة راحة مائية قصيرة.',
    tradeNames: 'Baycox, Amprol, Coccistop, Dicla-Vet' 
  },
  { 
    id: 'd16-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [16], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فاصل كيميائي ضروري لتنظيف القنوات الهضمية ومنع حدوث تداخلات بين مضاد الكوكسيديا القلوي ومضاد الكلوستريديا اللاحق.', 
    mixingRules: 'مياه عذبة نقية تماماً وبدرجة حرارة الغرفة.', 
    technicalSequence: 'راحة بين الدوائين تهدف لثبات الرقم الهيدروجيني للأمعاء وضمان فاعلية العلاج التالي.' 
  },
  { 
    id: 'd16-clos', 
    name: 'مضاد كلوستريديا', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'وقائي', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [16], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'منع نمو بكتيريا الكلوستريديا اللاهوائية التي تنشط غالباً كعدوى ثانوية للكوكسيديا، مسببةً تخمرات معوية وفقدان في الأوزان.', 
    mixingRules: 'يذاب جيداً ويضاف للخزان. يفضل استخدامه في مياه الشرب المسائية حيث يقل نشاط حركة الرياح وتهدأ الأمعاء.', 
    technicalSequence: 'جرعة ليلية متممة لبروتوكول حماية الأمعاء في منتصف الدورة، تضمن استقرار الوسط المعوي خلال فترة النوم.',
    tradeNames: 'Linco-Spectin, Bacitracin, Neomycin-Plus' 
  },
  { 
    id: 'd16-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [16], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'غسيل نهائي لخطوط الشرب من أي متبقيات كيماوية دوائية قد تترك طعماً مراً ينفر الطيور من الشرب صباحاً.', 
    mixingRules: 'مياه شرب عادية ونظيفة.', 
    technicalSequence: 'ختام فعال لليوم السادس عشر وتأمين لبداية دورة اليوم التالي.' 
  },

  // Day 17
  { 
    id: 'd17-cox', 
    name: 'مضاد كوكسيديا', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'وقائي', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [17], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استكمال كورس الوقاية من الكوكسيديا؛ حيث أن التوقف المبكر قد يسبب "ارتداداً" مرضياً وظهور عترات مقاومة للأدوية (Resistance).', 
    mixingRules: 'نفس قواعد اليوم السابق. تأكد من نظافة التانك من فضلات اليوم الماضي.', 
    technicalSequence: 'جرعة نهارية رئيسية لتدعيم الحماية المعوية.',
    tradeNames: 'Baycox, Coccistop, Amprol' 
  },
  { 
    id: 'd17-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [17], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية وتشطيف بين المواد الفعالة المتنوعة.', 
    mixingRules: 'مياه عذبة.', 
    technicalSequence: 'فاصل قبل الانتقال لجرعة مضاد الكلوستريديا المسائية.' 
  },
  { 
    id: 'd17-clos', 
    name: 'مضاد كلوستريديا', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'وقائي', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [17], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تأكيد القضاء على السموم المعوية البكتيرية ومنع حدوث أي انتفاخات أو إسهالات بنية اللون.', 
    mixingRules: 'خلط جيد ومستمر.', 
    technicalSequence: 'جرعة ليلية تدعم استقرار الوسط المعوي خلال فترة النوم.',
    tradeNames: 'Linco-Spectin, Neomycin, Bacitracin' 
  },
  { 
    id: 'd17-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [17], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استراحة لإعادة التوازن المائي للطيور.', 
    mixingRules: 'مياه نظيفة.', 
    technicalSequence: 'ختام اليوم السابع عشر.' 
  },

  // Day 18
  { 
    id: 'd18-cox', 
    name: 'مضاد كوكسيديا', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'وقائي', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [18], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'الوصول لأقصى حماية للأمعاء قبل طفرة الوزن الكبرى. إنهاء الكورس بانتظام يضمن خلو العنبر من بويضات الكوكسيديا الناضجة.', 
    mixingRules: 'إذابة كلية. يفضل استخدام مياه مفلترة لرفع كفاءة المواد الفعالة في اليوم الأخير.', 
    technicalSequence: 'الجرعة النهارية الأخيرة لهذا الكورس، تليها فترة راحة فسيولوجية.',
    tradeNames: 'Baycox, Dicla-Vet, Amprol' 
  },
  { 
    id: 'd18-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [18], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'غسيل للأمعاء من متبقيات الأدوية الوقائية الثقيلة.', 
    mixingRules: 'مياه ناصعة خالية من الإضافات.', 
    technicalSequence: 'راحة بين الكورسات النهائية.' 
  },
  { 
    id: 'd18-clos', 
    name: 'مضاد كلوستريديا', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'وقائي', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [18], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تأمين نهائي للحالة المعوية وضمان عدم نشاط أي بكتيريا ضارة بعد كورس الأدوية.', 
    mixingRules: 'خلط متجانس وتغطية الخزان.', 
    technicalSequence: 'الجرعة الليلية الختامية لهذا الكورس، تمهيداً ليوم الترميم والتعويض.',
    tradeNames: 'Linco-Spectin, Colistin-Plus' 
  },
  { 
    id: 'd18-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [18], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تطهير نهائي للأمعاء والخطوط.', 
    mixingRules: 'مياه عذبة.', 
    technicalSequence: 'ختام اليوم الثامن عشر بنجاح.' 
  },

  // Day 19
  { 
    id: 'd19-pro', 
    name: 'بروبيوتيك (بكتريا نافعة)', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'تأسيس', 
    usageType: 'ضروري', 
    recommendedHours: 6, 
    targetDays: [19], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'إعادة التوازن الميكروبي المعوي (Gut Flora) بعد الأدوية الوقائية، لتنشيط الهضم ورفع المناعة الموضعية للأمعاء.', 
    mixingRules: 'يستخدم ماء مبرد وخالي تماماً من أي مطهرات (كالكلور) لضمان حيوية البكتيريا النافعة.', 
    technicalSequence: 'جرعة صباحية استراتيجية لتحسين كفاءة الهضم في مطلع الأسبوع الثالث.',
    tradeNames: 'Bio-Top, Pro-B, Bactocin' 
  },
  { 
    id: 'd19-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [19], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة هضمية للسماح للبكتيريا النافعة بالارتباط بجدران الأمعاء دون تداخل دوائي.', 
    mixingRules: 'مياه نظيفة ناصعة.', 
    technicalSequence: 'فاصل زمني فني يمهد لجرعة المنشط الكبدي.' 
  },
  { 
    id: 'd19-hepato', 
    name: 'منشط كبد', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'كلوي/كبد', 
    usageType: 'ضروري', 
    recommendedHours: 6, 
    targetDays: [19], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تنقية وتطهير الكبد من نواتج تمثيل الأدوية الكيماوية الوقائية ورفع كفاءة التمثيل الغذائي لمواكبة بناء الأوزان.', 
    mixingRules: 'يرج جيداً قبل الاستخدام ويضاف للخزان الرئيسي.', 
    technicalSequence: 'جرعة نهارية وسطية لرفع معدل النشاط الحيوي للبدن.',
    tradeNames: 'Hepato-Vet, Liver-Tone, Hepa-Plus' 
  },
  { 
    id: 'd19-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [19], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تشطيف للأمعاء ومنع الإجهاد الناتج عن الأدوية المتتابعة.', 
    mixingRules: 'مياه عذبة عادية.', 
    technicalSequence: 'فاصل قبل جرعة الغسيل الكلوي المسائية.' 
  },
  { 
    id: 'd19-renal', 
    name: 'غسيل كلوي', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'كلوي/كبد', 
    usageType: 'ضروري', 
    recommendedHours: 6, 
    targetDays: [19], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'غسيل للأنابيب الكلوية للتخلص من الأملاح المترسبة ومخلفات الأدوية، وحماية المفاصل من التهاب اليوريكات (Gout).', 
    mixingRules: 'خلط جيد ومستمر لضمان توزيع المواد الفوارة والمفتتة للأملاح.', 
    technicalSequence: 'جرعة ليلية ختامية لدورة التطهير العلاجية التي تلي الأدوية الوقائية.',
    tradeNames: 'Renal-V, Nephro-Guard, Kidney-Clean' 
  },
  { 
    id: 'd19-water3', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [19], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تطهير نهائي وراحة شاملة للجسم.', 
    mixingRules: 'مياه نظيفة عذبة.', 
    technicalSequence: 'ختام اليوم التاسع عشر؛ القطيع الآن نظيف وجاهز لنمو هائل.' 
  },

  // Day 20
  { 
    id: 'd20-pro', 
    name: 'بروبيوتيك (بكتريا نافعة)', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'تأسيس', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [20], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'ترسيخ استعمار البكتيريا الصديقة في الأمعاء تزاماً مع ذروة استهلاك العلف اليومي، لمنع ميكروبات البيئة من احتلال أي موقع شاغر في الجهاز الهضمي.', 
    mixingRules: 'استخدام ماء مبرد. تجنب وجود مطهرات أو رواسب صابون في الأدوات المستخدمة للخلط.', 
    technicalSequence: 'جرعة صباحية نهارية ناعمة تدعم الحالة المناعية العامة للأمعاء.',
    tradeNames: 'Bio-Top, Pro-B' 
  },
  { 
    id: 'd20-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [20], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة فيسيولوجية للأعصاب والأمعاء؛ للسماح للبكتيريا النافعة بالانتشار الهادئ.', 
    mixingRules: 'مياه عذبة نقية.', 
    technicalSequence: 'فاصل راحة بين البروبيوتيك وفيتامينات B-K.' 
  },
  { 
    id: 'd20-bk', 
    name: 'فيتامين B-K (ب.ك كولين)', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [20], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'حماية الجهاز الدوري وتوفير فيتامين K الضروري لتجلط الدم، ومنع نقص فيتامينات B التي قد تسبب اعتلالات عصبية في الأعمار النشطة.', 
    mixingRules: 'يذاب في التانك مباشرة مع تقليب جيد. يفضل استهلاك السقية في المساء.', 
    technicalSequence: 'جرعة مسائية ختامية للأسبوع الثالث، تضمن استقرار الحالة الصحية والبدنية للقطيع.' 
  },
  { 
    id: 'd20-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [20], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تشطيف نهائي وتأمين للأمعاء قبل الراحة الليلية الكبرى.', 
    mixingRules: 'مياه عذبة نظيفة خالية من الإضافات.', 
    technicalSequence: 'نهاية الأسبوع الثالث بنجاح؛ الأسبوع القادم هو أسبوع الكتلة العضلية.' 
  },

  // Day 21
  { 
    id: 'd21-bk', 
    name: 'فيتامين B-K (ب.ك كولين)', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [21], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'مع بداية الأسبوع الرابع ونمو الكتلة العضلية الضخمة، يحمي فيتامين K من أي تمزقات وعائية دقيقة ناتجة عن ضغط الوزن الزائد، بينما يدعم فيتامين B تمثيل البروتين العضلي المكثف.', 
    mixingRules: 'يذاب في التانك مباشرة مع تقليب جيد لضمان تجانس المكونات. يفضل تقديمه في فترات الصباح الباكر.', 
    technicalSequence: 'جرعة استهلالية نهارية للأسبوع الرابع، تهدف لتحقيق أعلى معدل تحويل بروتيني وضمان سلامة الجهاز الدوري.',
    tradeNames: 'B-Complex Plus, Vit-B-K, Hepatic-Choline' 
  },
  { 
    id: 'd21-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [21], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية وتشطيف معوي للسماح للجسم بمعالجة الفيتامينات قبل تقديم مضاد السموم.', 
    mixingRules: 'مياه نظيفة نقية.', 
    technicalSequence: 'فاصل راحة للأمعاء يمهد لجرعة التطهير الكبدي المسائية.' 
  },
  { 
    id: 'd21-tox', 
    name: 'مضاد سموم فطرية', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'سموم', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [21], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'مواجهة مسببات السموم الفطرية الكامنة في علف النامي (Grower) الذي يتميز بتركيز طاقة وبروتين عالي. حماية الكبد ضرورية لمنع حدوث متلازمة الموت المفاجئ (SDS).', 
    mixingRules: 'يضاف للخزان مباشرة مع رج العبوة. يفضل استخدام مياه نظيفة جداً لرفع كفاءة تكسير السموم.', 
    technicalSequence: 'جرعة ليلية وقائية هامة لسلامة الأعضاء الحيوية (الكبد والكلى) خلال قمة فترة التسمين.',
    tradeNames: 'Anti-Tox, Myco-Nil, Toxi-Guard' 
  },
  { 
    id: 'd21-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [21], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة ليلية ختامية وتشطيف لخطوط الشرب من متبقيات مضاد السموم.', 
    mixingRules: 'مياه عذبة نقية.', 
    technicalSequence: 'ختام فعال لليوم الحادي والعشرين وبداية مرحلة الكتلة العضلية الحقيقية.' 
  },

  // Day 22
  { 
    id: 'd22-elec', 
    name: 'إليكتروليت (أملاح معدنية)', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'داعم', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [22], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'موازنة الضغط الأسموزي ومنع الجفاف الخلوي في ظل تضخم حجم الطائر وزيادة معدلات الأيض (Metabolism) التي ترفع حرارة الجسم الداخلية بشكل طبيعي.', 
    mixingRules: 'إذابة تامة حتى الاختفاء الكلي للرواسب الملحيّة لضمان عدم حدوث إسهالات ناتجة عن خلل التركيز.', 
    technicalSequence: 'جرعة نهارية لتوفير الاستقرار الهيدروليكي والبدني للطائر خلال ساعات ذروة الاستهلاك والنشاط.',
    tradeNames: 'Punch, Electrolyte-Vet, Hydra-Charge' 
  },
  { 
    id: 'd22-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [22], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة هضمية وتشطيف مائي فوري قبل الدخول في كورس الأحماض المعويية.', 
    mixingRules: 'مياه عذبة نقية.', 
    technicalSequence: 'فاصل فني ضروري لمنع حدوث أي تفاعل كيميائي بين الأملاح والأحماض في الأمعاء.' 
  },
  { 
    id: 'd22-acids', 
    name: 'أحماض عضوية', 
    unit: 'سم³/لتر', 
    doseValue: 0.5, 
    category: 'داعم', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [22], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تحسين حموضة الوسط المعوي للوصول لأقصى كفاءة لهضم البروتين، وتثبيط أي نمو بكتيري ضار قد يظهر نتيجة زيادة كميات العلف المستهلكة في هذا العمر.', 
    mixingRules: 'يضاف حسب التوصية التركيزية للمنتج. يراعى غسل أدوات القياس جيداً.', 
    technicalSequence: 'جرعة ليلية تدعم التوازن الميكروبي والتمثيل الغذائي خلال ساعات السكون البنائي.',
    tradeNames: 'Acid-Way, Pro-Acid, Formic-Vet' 
  },

  // Day 23
  { 
    id: 'd23-bk', 
    name: 'فيتامين B-K (ب.ك كولين)', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [23], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تأمين سلامة الأوعية الدموية وقوة الأربطة العضلية، حيث يمثل هذا العمر قمة منحنى التحويل الغذائي (Peak Growth Period) والحاجة لعوامل التجلط والتمثيل.', 
    mixingRules: 'خلط متجانس وتقليب جيد في الخزان الرئيسي لمنع ترسب مادة الكولين.', 
    technicalSequence: 'جرعة نهارية طويلة لضمان ثبات الاستقرار الحيوي ودعم عمليات البناء العضلي المكثفة.',
    tradeNames: 'B-Complex Plus, Hepatic-Choline' 
  },
  { 
    id: 'd23-water', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [23], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فترة أمان وحيادية كيميائية تامة؛ تسمح للكبد بمعالجة الفيض الهائل من العناصر وتفريغ الكلى من أي مخلفات بروتينية زائدة.', 
    mixingRules: 'مياه وفيرة ونظيفة جداً وبدرجة حرارة مريحة.', 
    technicalSequence: 'راحة ليلية ختامية تعقب الجرعة الطويلة، تمهد لاستقبال فيتامينات تعزيز القلب في اليوم اللاحق.' 
  },

  // Day 24
  { 
    id: 'd24-ese', 
    name: 'فيتامين هـ + سيلينيوم', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [24], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'توفير حماية قوية لعضلة القلب (Myocardium) ضد الإجهاد الدوراني الناتج عن ضخ الدم لأوزان بدنية كبيرة، ودعم المفاصل والأربطة لمنع حدوث اعتلالات ميكانيكية.', 
    mixingRules: 'إذابة كلية وفورية في التانك. يمنع خلطه مع المطهرات أو الإضافات القلوية لضمان ثبات مركبات السيلينيوم.', 
    technicalSequence: 'جرعة نهارية مكثفة تمنع ظاهرة انكسار الأرجل أو العرج (Leg Problems) وتؤمن سلامة القلب قبل استكمال النمو النهائي.',
    tradeNames: 'E-Selen, Vit-E-Plus, Se-Guard' 
  },
  { 
    id: 'd24-water', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [24], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية وتشطيف شامل للأجهزة الداخلية بعد يوم من الدعم المعدني القوي.', 
    mixingRules: 'مياه نظيفة عذبة وبكميات وفيرة لضمان الترطيب الكافي.', 
    technicalSequence: 'راحة ليلية هادئة تعقب فترة النشاط العضلي الكبيرة.' 
  },

  // Day 25
  { 
    id: 'd25-ese', 
    name: 'فيتامين هـ + سيلينيوم', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [25], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'الاستمرار في بناء مخزون مضادات الأكسدة داخل الألياف العضلية، مما يحسن جودة اللحم اللاحقة ويرفع من قدرة الطائر على تحمل إجهاد التنفس.', 
    mixingRules: 'إذابة كلية في مياه نقية. تجنب استخدام مياه تحتوي على نسبة كلور عالية قد تدمر الفيتامين.', 
    technicalSequence: 'جرعة نهارية لتدعيم القوة البدنية والمناعية العامة في ذروة مرحلة التسمين.',
    tradeNames: 'E-Selen, Se-Plus, Vit-E-20' 
  },
  { 
    id: 'd25-water', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [25], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية ليلية تامة لإخلاء الكلى من متبقيات الفيتامينات وإعادة التوازن المائي الطبيعي.', 
    mixingRules: 'مياه عذبة نقية وبدرجة حرارة مريحة.', 
    technicalSequence: 'راحة ختام اليوم الخامس والعشرين؛ المرحلة قبل النهائية (Finish Phase) تبدأ قريباً.' 
  },

  // Day 26
  { 
    id: 'd26-acids', 
    name: 'أحماض عضوية', 
    unit: 'سم³/لتر', 
    doseValue: 0.5, 
    category: 'داعم', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [26], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'مع اقتراب نهاية الدورة وزيادة حمل العلف، تضمن الأحماض بيئة معوية حامضية تمنع نشاط السالمونيلا والقولونية، وتزيد من امتصاص الكالسيوم والفسفور لتدعيم الهيكل العظمي تحت الوزن الثقيل.', 
    mixingRules: 'إضافة دقيقة للخزان. تجنب خلطها مع الأدوية لعدم تغيير طبيعة الوسط المائي.', 
    technicalSequence: 'جرعة نهارية لتأمين الهضم السريع وتحويل العلف لكتلة عضلية بكفاءة عالية.',
    tradeNames: 'Acid-Way, Formic-Vet, Pro-Acid' 
  },
  { 
    id: 'd26-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [26], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية وتشطيف معوي للأحماض.', 
    mixingRules: 'مياه عذبة نقية.', 
    technicalSequence: 'فاصل زمني فني يمهد لجرعة فيتامين C المسائية.' 
  },
  { 
    id: 'd26-vitc', 
    name: 'فيتامين C', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 8, 
    targetDays: [26], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'فيتامين C يعمل كمضاد إجهاد حراري وتنفسي قوي، ويقلل من مستويات الكورتيزول في الدم، مما يحافظ على هدوء الطيور ونموها تحت ضغط الوزن الثقيل.', 
    mixingRules: 'يذاب في ماء مائل للبرودة لضمان فاعلية الفيتامين وتجنب تكسره بالحرارة.', 
    technicalSequence: 'جرعة مسائية تضمن استقرار الحالة العصبية والفسيولوجية وبناء الأنسجة الهادئ.' 
  },
  { 
    id: 'd26-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 6, 
    targetDays: [26], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تشطيف نهائي وراحة ليلية شاملة.', 
    mixingRules: 'مياه نظيفة عذبة.', 
    technicalSequence: 'ختام اليوم السادس والعشرين مع وزن قياسي وهدوء مثالي.' 
  },

  // Day 27
  { 
    id: 'd27-bk', 
    name: 'فيتامين B-K (ب.ك كولين)', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [27], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'حماية الأوعية الدموية المتضخمة من الانفجار المفاجئ (Aortic Rupture) وتوفير السيولة المناسبة والتبادل الأيضي للعناصر الصغرى في الأسبوع الأخير.', 
    mixingRules: 'تقليب جيد ومستمر لضمان عدم ترسب الكولين في قاع الخزان.', 
    technicalSequence: 'جرعة نهارية رئيسية لتدعيم الجهاز الدوري تحت ضغوط النمو القصوى.',
    tradeNames: 'B-Complex Plus, Hepatic-Choline' 
  },
  { 
    id: 'd27-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [27], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استراحة لإعادة التوازن المائي ومنع تراكم الفيتامينات الزائد.', 
    mixingRules: 'مياه عذبة نقية.', 
    technicalSequence: 'فاصل قبل كورس مضاد السموم المسائي.' 
  },
  { 
    id: 'd27-tox', 
    name: 'مضاد سموم فطرية', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'سموم', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [27], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تنظيف نهائي للكبد من السموم التراكمية لضمان جودة المنتج النهائي وحيوية الطائر في الأمتار الأخيرة من التسمين.', 
    mixingRules: 'يضاف حسب تركيز المنتج المعتمد. يفضل استخدامه في مياه نقية خالية من الكلور.', 
    technicalSequence: 'جرعة ليلية وقائية ختامية لكورس السموم، تضمن سلامة الأعضاء الحيوية قبل البيع.',
    tradeNames: 'Anti-Tox, Toxi-Guard, Myco-Nil' 
  },
  { 
    id: 'd27-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [27], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تطهير نهائي وراحة فسيولوجية.', 
    mixingRules: 'مياه شرب عادية ونظيفة.', 
    technicalSequence: 'ختام اليوم السابع والعشرين بنجاح تام.' 
  },

  // Day 28
  { 
    id: 'd28-ad3e_new', 
    name: 'فيتامينات أد3هـ', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [28], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'دعم النمو النهائي وتوفير الفيتامينات الذائبة في الدهون لضمان جودة الأنسجة.', 
    mixingRules: 'خلط جيد في الخزان.', 
    technicalSequence: 'جرعة نهارية/ليلية شاملة.' 
  },
  { 
    id: 'd28-water', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [28], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية.', 
    mixingRules: 'مياه نظيفة.', 
    technicalSequence: 'ختام اليوم.' 
  },

  // Day 29
  { 
    id: 'd29-ad3e_new', 
    name: 'فيتامينات أد3هـ', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [29], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'استكمال جرعات الفيتامينات لرفع الكفاءة الحيوية.', 
    mixingRules: 'خلط جيد.', 
    technicalSequence: 'جرعة نهارية مكثفة.' 
  },
  { 
    id: 'd29-water', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [29], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة ليلية.', 
    mixingRules: 'ماء نظيف.', 
    technicalSequence: 'ختام اليوم.' 
  },

  // Day 30
  { 
    id: 'd30-renal', 
    name: 'غسيل كلوي', 
    unit: 'سم³/لتر', 
    doseValue: 0.5, 
    category: 'داعم', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [30], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'الحفاظ على ثبات معامل التحويل الغذائي (FCR) في أعلى مستوياته ومنع أي هدر علفي عبر الإسهالات البسيطة، مما يضمن أقصى استفادة من كل جرام علف.', 
    mixingRules: 'إضافة دقيقة حسب الحاجة لضبط الرقم الهيدروجيني للأمعاء (pH). يفضل استخدامه مع مياه نظيفة.', 
    technicalSequence: 'جرعة نهارية ضابطة لعمليات الهضم والامتصاص في بداية مرحلة التجهيز النهائي.',
    tradeNames: 'Renal-V, Nephro-Guard, Kidney-Clean' 
  },
  { 
    id: 'd30-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [30], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية وتشطيف مائي فني لمسار الجهاز الهضمي.', 
    mixingRules: 'مياه عذبة نقية.', 
    technicalSequence: 'فاصل قبل جرعة فيتامين C الوقائية.' 
  },
  { 
    id: 'd30-vitc', 
    name: 'فيتامين C', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [30], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'رفع المقاومة التنفسية وتخفيف ضغط الأكسجين داخل الخلايا في ظل الازدحام ونمو الأحشاء الداخلية ببطء مقارنة بالعضلات.', 
    mixingRules: 'يذاب تماماً في ماء نقي وبدرجة حرارة الغرفة. لا يترك في الخزان لفترة طويلة لعدم الأكسدة.', 
    technicalSequence: 'جرعة مسائية تضمن تبريداً داخلياً للجسم وتنفس غائر وهادئ خلال ساعات السكون.',
    tradeNames: 'Vitacid, C-Vet, Ascorbic-Vet' 
  },
  { 
    id: 'd30-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [30], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة نهائية وغسيل للأمعاء.', 
    mixingRules: 'مياه نظيفة عذبة.', 
    technicalSequence: 'نهاية اليوم الثلاثين بقطيع ممتاز وحيوية عالية.' 
  },

  // Day 31
  { 
    id: 'd31-bk', 
    name: 'فيتامين B-K (ب.ك كولين)', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [31], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'تأمين جودة الذبيحة منعاً لوجود "الأنزفة" أو البقع الدموية في الأنسجة تحت الجلد، وضمان ثبات قوام الألياف العضلية قبل مرحلة التسويق النهائية.', 
    mixingRules: 'يذاب بتركيز متوازن في مياه عذبة. تأكد من وصول الجرعة لكافة المشارب لضمان تجانس القطيع.', 
    technicalSequence: 'جرعة نهارية استقرار حيوية تهدف لرفع القيمة السوقية للمنتج النهائي.',
    tradeNames: 'B-Complex Plus, Vit-B-K' 
  },
  { 
    id: 'd31-water1', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [31], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة هضمية وفترة سماح للجسم بامتصاص الفيتامينات بفاعلية.', 
    mixingRules: 'مياه نظيفة نقية ناصعة.', 
    technicalSequence: 'فاصل راحة فني يمهد لجرعة مضاد السموم الختامية.' 
  },
  { 
    id: 'd31-tox', 
    name: 'مضاد سموم فطرية', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'سموم', 
    usageType: 'ضروري', 
    recommendedHours: 10, 
    targetDays: [31], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'التخلص من أي متبقيات سمية أخيرة في الكبد والكلى لضمان حصول المستهلك على منتج عالي الجودة وصحي، والحفاظ على نشاط الطائر قبل البيع.', 
    mixingRules: 'يضاف للخزان مباشرة مع تقليب جيد. يفضل استخدام مياه نظيفة خالية من الشوائب لرفع سرعة الامتصاص.', 
    technicalSequence: 'جرعة ليلية تطهيرية ختامية لكورس مضاد السموم في الدورة.',
    tradeNames: 'Anti-Tox, Toxi-Guard, Myco-Nil' 
  },
  { 
    id: 'd31-water2', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 2, 
    targetDays: [31], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية شاملة وتطهير نهائي لخطوط الشرب.', 
    mixingRules: 'مياه عذبة نظيفة.', 
    technicalSequence: 'ختام فعال لليوم الحادي والثلاثين وجاهزية تامة للتسويق.' 
  },

  // Day 32
  { 
    id: 'd32-vitc', 
    name: 'فيتامين C', 
    unit: 'جرام/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [32], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'الحفاظ على حيوية الطائر وبرودة جسمه الداخلية، وتقليل فاقد الوزن الناتج عن اللهاث أو الإجهاد الحراري في الأمتار الأخيرة قبل التحميل.', 
    mixingRules: 'إذابة تامة في مياه ناصعة وبدرجة حرارة مريحة للشرب. يمنع تكرار الغليان أو التعرض المباشر للشمس.', 
    technicalSequence: 'جرعة نهارية تهدف لتثبيت السعة التنفسية والحالة العامة للقطيع في يوم البيع أو ما قبله.',
    tradeNames: 'Vitacid, C-Vet, Ascorbic-Vet' 
  },
  { 
    id: 'd32-water', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [32], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية ليلية تامة لإخلاء الجسم من أي ترسبات فيتامينية قبل الذبح وبدء مرحلة الأمان.', 
    mixingRules: 'مياه عذبة نقية وفيرة.', 
    technicalSequence: 'راحة ليلية ختامية تمهد لليوم الثالث والثلاثين.' 
  },

  // Day 33
  { 
    id: 'd33-bk', 
    name: 'فيتامين B-K (ب.ك كولين)', 
    unit: 'سم³/لتر', 
    doseValue: 1, 
    category: 'فيتامينات', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [33], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'الدعم النهائي للجهاز الدوري والكولين لتمثيل آخر جرامات البروتين، وضمان تحمل الطائر لعمليات التحميل والنقل المجهدة لاحقاً.', 
    mixingRules: 'خلط جيد في الخزان وتأكد من وصول المياه لجميع أركان العنبر لضمان ثبات القطيع.', 
    technicalSequence: 'جرعة نهارية طويلة لضمان التماسك العضلي والحيوي لأوزان الدورة النهائية.',
    tradeNames: 'B-Complex Plus, Hepatic-Choline' 
  },
  { 
    id: 'd33-water', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 12, 
    targetDays: [33], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'راحة عضوية وتشطيف مائي شامل للأجهزة الداخلية بعد ختام كورس الفيتامينات.', 
    mixingRules: 'مياه نظيفة ناصعة وبكميات وفيرة.', 
    technicalSequence: 'ختام فعال وشامل لليوم الثالث والثلاثين؛ الدورة توشك على الانتهاء بنجاح.' 
  },

  // Day 34
  { 
    id: 'd34-water', 
    name: 'ماء نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 24, 
    targetDays: [34], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'بدء فترة سحب الأدوية (Withdrawal Period) الفعلية؛ حيث يتم الاعتماد على الماء النقي فقط لإخلاء الأنسجة من أي متبقيات كيماوية، مما يضمن أماناً تاماً وصحياً للمستهلك.', 
    mixingRules: 'مياه شرب نقية جداً وخالية من أي إضافات كيماوية أو دوائية.', 
    technicalSequence: 'يوم كامل من المياه النظيفة (24 ساعة) لغسيل الجسم الطبيعي وتطهير الأمعاء قبل عمليات التحميل.' 
  },

  // Day 35
  { 
    id: 'd35-water', 
    name: 'مياه نقي', 
    unit: 'لتر', 
    doseValue: 0, 
    category: 'راحة', 
    usageType: 'ضروري', 
    recommendedHours: 24, 
    targetDays: [35], 
    climates: ['بارد جدا', 'بارد', 'معتدل', 'حار', 'حار جدا'], 
    scientificExplanation: 'ضمان خلو الأنسجة والأعضاء الداخلية تماماً من أي متبقيات دوائية. هذا الإجراء يرفع من جودة المنتج النهائي ويحقق المعايير الصحية العالمية لإنتاج الدواجن.', 
    mixingRules: 'مياه عذبة تماماً وفيرة وبدرجة حرارة مريحة لتشجيع الطيور على الشرب بكثرة.', 
    technicalSequence: 'مراحل الغسيل المائي النهائي ممتدة حتى لحظة التحميل والبيع؛ لضمان أفضل منتج نهائي للسوق.' 
  },
];

